name: 'Sparse Checkout'
description: 'Perform a sparse checkout from the repository'
inputs:
  pattern:
    description: 'Patterns to checkout'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        BRANCH="${GITHUB_REF/#refs\/heads\//}"
        git clone --filter=blob:none --no-checkout --depth 1 --sparse $REPO .
        # TODO: support --cone
        git sparse-checkout init
        git sparse-checkout set ${{ inputs.pattern }}
        # Fetch and checkout the branch being tested
        git fetch --no-tags --prune --progress --depth=1 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
        git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH
      shell: bash
